### ISSUE TITLE
Typing of `array_entry.read_keyword()`

### ISSUE THREAD

**Issue by sebastianvitterso** [equinor/ecl-data-io#38]
https://github.com/equinor/ecl-data-io/blob/38b33b5ed44faf60344ca305a8bf05454f8d5108/src/ecl_data_io/array_entry.py#L38-L46

Looking at the above code, I'd love if this function could be typed to return a string, because currently (because `self._keyword = None`) it is implicitly typed to return `None`!

**Comment by eivindjahren** [comment]
I have started acting on this issue now. Will try to get thpe-hints of the public API in the next version.

**Comment by sebastianvitterso** [comment]
Nice! Can I ask - what is equinor/ecl-data-io's release schedule? I see the previous release was in July, but I don't know if there has been any active development since then..?

**Comment by eivindjahren** [comment]
@sebastianvitterso There is no set schedule. My plan is to get https://github.com/equinor/ecl-data-io/pull/40 in, create a beta release I can test against `xtgeo`. Then I will release v3.0.0 . The major version bump is due to dropping support for python 3.7 and a minor difference in error handling. I expect to get this in this week :)
